version: "3"

services:
  backend:
    build: .
    ports:
      - 3000
    volumes:
      - ./:/application/
    healthcheck:
      test: ["CMD", "ping", "http://localhost:3000"]
      interval: 10s
      retries: 3
    scale: 3
  server:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf